//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.Resources.Texts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskManager.Resources.Texts.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DialogCancel {
            get {
                return ResourceManager.GetString("DialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DialogError {
            get {
                return ResourceManager.GetString("DialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string DialogOk {
            get {
                return ResourceManager.GetString("DialogOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string TaskDetailDescription {
            get {
                return ResourceManager.GetString("TaskDetailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a description.
        /// </summary>
        internal static string TaskDetailDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("TaskDetailDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date.
        /// </summary>
        internal static string TaskDetailExpirationDate {
            get {
                return ResourceManager.GetString("TaskDetailExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TaskDetailName {
            get {
                return ResourceManager.GetString("TaskDetailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill the name of the task.
        /// </summary>
        internal static string TaskDetailNamePlaceholder {
            get {
                return ResourceManager.GetString("TaskDetailNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string TaskDetailPrioridad {
            get {
                return ResourceManager.GetString("TaskDetailPrioridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string TaskDetailRemove {
            get {
                return ResourceManager.GetString("TaskDetailRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task is about to be deleted. Do you want to continue?.
        /// </summary>
        internal static string TaskDetailRemoveQuestion {
            get {
                return ResourceManager.GetString("TaskDetailRemoveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string TaskDetailSave {
            get {
                return ResourceManager.GetString("TaskDetailSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify all the fields of the task.
        /// </summary>
        internal static string TaskDetailSaveError {
            get {
                return ResourceManager.GetString("TaskDetailSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task will be saved. Do you want to continue?.
        /// </summary>
        internal static string TaskDetailSaveQuestion {
            get {
                return ResourceManager.GetString("TaskDetailSaveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string TaskDetailTitle {
            get {
                return ResourceManager.GetString("TaskDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task list.
        /// </summary>
        internal static string TaskListTitle {
            get {
                return ResourceManager.GetString("TaskListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string TaskPriorityHigh {
            get {
                return ResourceManager.GetString("TaskPriorityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string TaskPriorityLow {
            get {
                return ResourceManager.GetString("TaskPriorityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string TaskPriorityMedium {
            get {
                return ResourceManager.GetString("TaskPriorityMedium", resourceCulture);
            }
        }
    }
}
